"""Editor/test protocols for celld's native Monty capabilities.

The native compiler supplies Context inside a worker. In ordinary Python, use
a test double implementing this protocol; these declarations do not start a VM.
"""
from typing import Any, Callable, Protocol, TypeVar, TypedDict

T = TypeVar("T")


class FetchResponse(TypedDict):
    status: int
    headers: dict[str, str]
    body: str


class Storage(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def put(self, key: str, value: Any) -> None: ...
    def delete(self, key: str) -> bool: ...
    def list(self, prefix: str = "", limit: int = 1000, reverse: bool = False) -> dict[str, Any]: ...
    def delete_all(self) -> None: ...
    def sync(self) -> None: ...
    def sql(self, query: str, *bindings: Any) -> list[dict[str, Any]]: ...
    def transaction(self, callback: Callable[["Storage"], T]) -> T: ...
    def get_alarm(self) -> int | None: ...
    def set_alarm(self, timestamp_ms: int) -> None: ...
    def delete_alarm(self) -> None: ...


class ObjectStub(Protocol):
    async def call(self, function: str, **args: Any) -> Any: ...


class Context(Protocol):
    id: str | None
    name: str | None
    env: dict[str, str | int | float | bool | None]
    storage: Storage
    caller: dict[str, Any]
    client: dict[str, Any]
    call_id: str | None
    attempt: int
    alarm: dict[str, Any] | None

    def object(self, binding: str, name: str) -> ObjectStub: ...
    async def fetch(self, url: str, method: str = "GET", headers: dict[str, str] | None = None,
                    body: str | None = None) -> FetchResponse: ...
    async def sleep(self, seconds: float) -> None: ...
    def now(self) -> int: ...
    def uuid(self) -> str: ...
    def log(self, message: Any) -> None: ...
